export const CHANNEL_TYPES = [
  { key: '1', label: 'OpenAI' },
  { key: '3', label: 'Azure' },
  { key: '8', label: 'Custom' },
  { key: '14', label: 'Claude' },
  { key: '18', label: 'Gemini' },
  { key: '30', label: 'Midjourney' },
  { key: '40', label: '通义千问' },
  { key: '41', label: '混元' },
  { key: '42', label: '文心一言' },
  { key: '43', label: '讯飞星火' },
  { key: '44', label: 'Deepseek' },
  { key: '45', label: '智谱 ChatGLM' },
  { key: '46', label: 'Moonshot' },
  { key: '47', label: 'Ollama' },
  { key: '50', label: 'Suno' },
  { key: '51', label: 'Dify' },
  { key: '52', label: 'SiliconFlow' },
  { key: '53', label: 'Mistral' },
  { key: '54', label: 'xAI / Grok' },
  { key: '55', label: 'Groq' },
  { key: '56', label: 'Together AI' },
  { key: '57', label: 'Perplexity' },
  { key: '58', label: 'Codex' },
  { key: '100', label: '🔧 自定义渠道' },
];
